package rvmat

// Known pixel shader IDs observed in game data.
var knownPixelShaderID = map[string]struct{}{
	"TerrainX":                            {},
	"Super":                               {},
	"Multi":                               {},
	"Terrain1":                            {},
	"Terrain3":                            {},
	"TreeAdv":                             {},
	"Terrain5":                            {},
	"Terrain4":                            {},
	"Terrain9":                            {},
	"Terrain2":                            {},
	"Terrain8":                            {},
	"Terrain7":                            {},
	"Terrain15":                           {},
	"Terrain13":                           {},
	"Terrain11":                           {},
	"TreeAdvTrunk":                        {},
	"TerrainSNX":                          {},
	"Skin":                                {},
	"Terrain6":                            {},
	"Terrain12":                           {},
	"Grass":                               {},
	"SuperHair":                           {},
	"Terrain10":                           {},
	"NormalMapSpecularMap":                {},
	"Normal":                              {},
	"NormalMapSpecularDIMap":              {},
	"NormalMapDetailSpecularDIMap":        {},
	"NormalMapDiffuse":                    {},
	"Terrain14":                           {},
	"Tree":                                {},
	"CalmWater":                           {},
	"Detail":                              {},
	"NormalMapDetailMacroASSpecularDIMap": {},
	"NormalMapMacroASSpecularDIMap":       {},
	"super":                               {},
	"AlphaShadow":                         {},
	"Glass":                               {},
	"AlphaNoShadow":                       {},
	"DetailMacroAS":                       {},
	"NormalMap":                           {},
	"NormalMapDetailSpecularMap":          {},
	"SuperExt":                            {},
}

// Known vertex shader IDs observed in game data.
var knownVertexShaderID = map[string]struct{}{
	"Terrain":               {},
	"Super":                 {},
	"Multi":                 {},
	"TreeAdv":               {},
	"TreeAdvTrunk":          {},
	"Skin":                  {},
	"NormalMap":             {},
	"Grass":                 {},
	"Basic":                 {},
	"TreeNoFade":            {},
	"NormalMapDiffuseAlpha": {},
	"VSTerrain":             {},
	"NormalMapAS":           {},
	"CalmWater":             {},
	"TreeAdvModNormals":     {},
	"Tree":                  {},
	"TreeADV":               {},
	"super":                 {},
	"Glass":                 {},
	"BasicAS":               {},
	"NormalMapDiffuse":      {},
	"Treenofade":            {},
	"BasicAlpha":            {},
}

// Known stage names observed in game data.
var knownStageNames = map[string]struct{}{
	"Stage0":    {},
	"Stage1":    {},
	"Stage2":    {},
	"Stage3":    {},
	"Stage4":    {},
	"Stage5":    {},
	"Stage6":    {},
	"Stage7":    {},
	"Stage8":    {},
	"Stage9":    {},
	"Stage10":   {},
	"Stage11":   {},
	"Stage12":   {},
	"Stage13":   {},
	"Stage14":   {},
	"StageTI":   {},
	"StageLast": {},
}

// Known procedural texture functions observed in game data.
var knownProceduralFns = map[string]struct{}{
	"color":        {},
	"fresnel":      {},
	"fresnelglass": {},
	"irradiance":   {},
}

// Known texture tags observed in procedural color() references.
var knownTextureTags = map[string]struct{}{
	"as":        {},
	"ca":        {},
	"cdt":       {},
	"co":        {},
	"dt":        {},
	"dtsmdi":    {},
	"mask":      {},
	"mc":        {},
	"mca":       {},
	"nohq":      {},
	"smdi":      {},
	"ads":       {},
	"adshq":     {},
	"cat":       {},
	"draftlco":  {},
	"gs":        {},
	"lca":       {},
	"lco":       {},
	"mco":       {},
	"no":        {},
	"noex":      {},
	"nof":       {},
	"nofex":     {},
	"nofhq":     {},
	"non":       {},
	"nopx":      {},
	"nsex":      {},
	"nshq":      {},
	"novhq":     {},
	"pr":        {},
	"raw":       {},
	"sky":       {},
	"sm":        {},
	"normalmap": {},
}
